version: "3.4"
services:
    fastjson_node:
        build: ./fastjson_node
        container_name: fastjson_node
        ports:
            - "8090:8090"
        cap_add:
            - ALL
        sysctls:
            - net.ipv4.ip_forward=1
            - net.ipv4.conf.default.rp_filter=0
            - net.ipv4.conf.all.rp_filter=0
        privileged: true
        networks:
            net_160_net0:
                ipv4_address: 10.160.0.254
        volumes:
            - ./share:/data
        labels:
            org.seedsecuritylabs.seedemu.meta.role: "WebService-fastjson"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "net_161_net0"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.160.0.254/24"

    infected_node:
        build: ./infected_node
        container_name: infected_node
        cap_add:
            - ALL
        sysctls:
            - net.ipv4.ip_forward=1
            - net.ipv4.conf.default.rp_filter=0
            - net.ipv4.conf.all.rp_filter=0
        privileged: true
        networks:
            net_160_net0:
                ipv4_address: 10.160.0.10
        volumes:
            - ./share:/data
        labels:
            org.seedsecuritylabs.seedemu.meta.role: "Client-Node"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "net_161_net0"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.160.0.10/24"

networks:
    net_160_net0:
        driver_opts:
            com.docker.network.driver.mtu: 1500
        ipam:
            config:
                - subnet: 10.160.0.0/24
        labels:
            org.seedsecuritylabs.seedemu.meta.type: "local"
            org.seedsecuritylabs.seedemu.meta.scope: "160"
            org.seedsecuritylabs.seedemu.meta.name: "net0"
            org.seedsecuritylabs.seedemu.meta.prefix: "10.160.0.0/24"
